export const employeeAddFields = {
  basicFields: [
    {
      label: "Name",
      name: "basicField.name",
      type: "text",
      placeholder: "Name",
      required: true,
    },
    {
      label: "Employee Id",
      name: "basicField.empId",
      type: "text",
      placeholder: "Employee Id",
      required: true,
    },
    {
      label: "Company Email",
      name: "basicField.email",
      type: "text",
      placeholder: "Email",
      required: true,
    },
    {
      label: "Password",
      name: "basicField.password",
      type: "text",
      placeholder: "Password",
      required: true,
    },
    {
      label: "Mobile",
      name: "basicField.phoneNumber",
      type: "text",
      placeholder: "Mobile",
      required: true,
    },
    {
      label: " Parant's Contact Number",
      name: "basicField.parantNumber",
      type: "phoneNumber",
      placeholder: "Parant's Contact Number",
      required: true,
    },
    {
      label: " Emergency Contact Number",
      name: "basicField.emengencyNumber",
      type: "phoneNumber",
      placeholder: "Emergency Contact Number",
      required: true,
    },
    {
      label: "D.O.B.",
      name: "basicField.dob",
      type: "date",
      placeholder: "D.O.B",
      required: true,
    },
    {
      label: "Designation",
      name: "basicField.jobRole",
      type: "text",
      placeholder: "Designation",
      required: true,
    },
    {
      label: "Department",
      name: "basicField.department",
      type: "text",
      placeholder: "Department",
      required: true,
    },
    {
      label: "Job Location",
      name: "basicField.jobLocation",
      type: "select",
      placeholder: "Job Location",
      options: [
        { value: "BIHAR", label: "BIHAR" },
        { value: "DEHRADUN", label: "DEHRADUN" },
      ],
      required: true,
    },
    {
      label: "Personal Email id",
      name: "basicField.personalEmail",
      type: "text",
      placeholder: "Email",
      required: true,
    },
    {
      label: "CTC",
      name: "basicField.ctc",
      type: "text",
      placeholder: "CTC",
      required: true,
    },
    {
      label: "PAN Card Number",
      name: "basicField.pan",
      type: "text",
      placeholder: "PAN Card Number",
      required: true,
    },
    {
      label: "Aadhar Card Number",
      name: "basicField.aadhar",
      type: "number",
      placeholder: "Aadhar Card Number",
      required: true,
    },
    {
      label: "Address",
      name: "basicField.address",
      type: "textarea",
      placeholder: "Address",
      required: true,
    },
    {
      label: "Gender",
      name: "basicField.gender",
      type: "select",
      options: [
        { value: "Male", label: "Male" },
        { value: "Female", label: "Female" },
        { value: "Other", label: "Other" },
      ],
      required: true,
    },
    {
      label: "Status",
      name: "basicField.status",
      type: "select",
      options: [
        { value: "ACTIVE", label: "Active" },
        { value: "INACTIVE", label: "Inactive" },
      ],
      required: true,
    },
    {
      label: "Joining Date",
      name: "basicField.doj",
      type: "date",
      placeholder: "Joining Date",
      required: true,
    },
    {
      label: "Last Working Date (if applicable)",
      name: "basicField.lwd",
      type: "date",
      placeholder: "Last Working Date",
      required: false,
    },
    {
      label: "Role",
      name: "basicField.role",
      type: "select",
      options: [
        // { value: "ADMIN", label: "admin" },
        { value: "EMPLOYEE", label: "employee" },
        { value: "EMPLOYEE", label: "HR" },
      ],
      required: true,
    },
    {
      label: "Give all permissions",
      name: "permissions",
      type: "checkbox",
      trueValue: "all",
      falseValue: "choose",
    },
    {
      label: "Dashboard",
      name: "permissions.dashboard",
      type: "multiselect",
      display: "horizontal",
      options: [{ value: "view", label: "view" }],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Employees",
      name: "permissions.employee",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Database Management",
      name: "permissions.database",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Ground Leads Management",
      name: "permissions.leadmanage",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Ground Leads",
      name: "permissions.lead",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Clients",
      name: "permissions.client",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Task Management",
      name: "permissions.taskmanage",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Users & Admission Enquiries",
      name: "permissions.userAdmission",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Colleges",
      name: "permissions.college",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Enquiry",
      name: "permissions.enquiry",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Invoice",
      name: "permissions.invoice",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Document formats",
      name: "permissions.format",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "B2B",
      name: "permissions.b2b",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Salary slip",
      name: "permissions.salary",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Jobs",
      name: "permissions.job",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Offers",
      name: "permissions.offer",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Applications",
      name: "permissions.application",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Blogs",
      name: "permissions.blog",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Attendance",
      name: "permissions.attendance",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Batch",
      name: "permissions.batch",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Faculty",
      name: "permissions.faculty",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Fees",
      name: "permissions.fee",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Students",
      name: "permissions.student",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Profile picture",
      name: "basicField.profilePic",
      type: "file",
      required: true,
    },
  ],
  bankFields: [
    {
      label: "Bank Account name",
      name: "bankField.bankName",
      type: "text",
      required: true,
    },
    {
      label: "Bank Account number",
      name: "bankField.bankAccountNumber",
      type: "text",
      required: true,
    },
    {
      label: "IFSC code",
      name: "bankField.ifscCode",
      type: "text",
      required: true,
    },
    {
      label: "Bank Passbook",
      name: "bankField.passbook",
      type: "file",
      folder: "employee/EmployeeBankDetails",
    },
  ],
  docFields: [
    {
      label: "Aadhar Document ",
      name: "docField.adharDocument",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "PAN Document ",
      name: "docField.panDocument",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "10th Marksheet ",
      name: "docField.tenthMarksheet",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "12th Marksheet ",
      name: "docField.twelvethMarksheet",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "UG Marksheet ",
      name: "docField.ugMarksheet",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "PG Marksheet ",
      name: "docField.pgMarksheet",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Resume ",
      name: "docField.resume",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Last Company salary slip ",
      name: "docField.salarySlip",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Last Company Experience letter ",
      name: "docField.expLetter",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Last Company Internship Certificate (if applicable) ",
      name: "docField.intershipcert",
      type: "file",
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Last Company Offer letter",
      name: "docField.offerLetter",
      type: "file",
      required: true,
      folder: "employee/OnBoardingDocuments",
    },
    {
      label: "Other Documents ",
      name: "docField.otherdoc",
      type: "file",
      folder: "employee/OnBoardingDocuments",
    },
  ],
  companyFields: [
    {
      label: "Company Contract",
      name: "companyField.contract",
      type: "file",
      required: true,
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Internship Certificate ",
      name: "docField.intershipcert",
      type: "file",
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Company Offer letter",
      name: "companyField.offerLetter",
      type: "file",
      required: true,
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Company ID",
      name: "companyField.idCard",
      type: "file",
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Relieving letter",
      name: "companyField.relievingLetter",
      type: "file",
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Experience letter",
      name: "companyField.expLetter",
      type: "file",
      folder: "employee/EuropassDocuments",
    },

    {
      label: "Salary slip",
      name: "companyField.salarySlip",
      type: "file",
      folder: "employee/EuropassDocuments",
    },
    {
      label: "Other Documents ",
      name: "docField.otherdoc",
      type: "file",
      folder: "employee/EuropassDocuments",
    },
  ],
  salaryFields: [
    {
      label: "Basic Salary",
      name: "earning.basicSalary",
      type: "number",
      required: true,
    },
    {
      label: "HRA (House Rent Allowance)",
      name: "earning.hra",
      type: "number",
    },
    {
      label: "Telephone Reimbursement",
      name: "earning.telephoneReimbursement",
      type: "number",
    },
    {
      label: "Bonus",
      name: "earning.bonus",
      type: "number",
    },
    {
      label: "LTA (Leave Travel Allowance)",
      name: "earning.lta",
      type: "number",
    },
    {
      label: "Special Allowance / Petrol Allowance",
      name: "earning.specialAllowancePetrolAllowance",
      type: "number",
    },
    {
      label: "Incentive",
      name: "earning.incentive",
      type: "number",
    },
  ],
  taxFields: [
    {
      label: "Income Tax",
      name: "tax.incomeTax",
      type: "number",
      required: true,
    },
    {
      label: "Provident Fund",
      name: "tax.providentFund",
      type: "number",
    },
    {
      label: "Professional Tax",
      name: "tax.professionalTax",
      type: "number",
    },
  ],
};

export const facultyAddFields = {
  basicFields: [
    {
      label: "Name",
      name: "basicField.name",
      type: "text",
      placeholder: "Name",
      required: true,
    },
    {
      label: "Employee Id",
      name: "basicField.empId",
      type: "text",
      placeholder: "Employee Id",
      required: true,
    },
    {
      label: "Company Email",
      name: "basicField.email",
      type: "text",
      placeholder: "Email",
      required: true,
    },
    {
      label: "Password",
      name: "basicField.password",
      type: "text",
      placeholder: "Password",
      required: true,
    },
    {
      label: "Mobile",
      name: "basicField.phoneNumber",
      type: "phoneNumber",
      placeholder: "Mobile",
      required: true,
    },
    {
      label: " Parant's Contact Number",
      name: "basicField.parantNumber",
      type: "phoneNumber",
      placeholder: "Parant's Contact Number",
      required: true,
    },
    {
      label: " Emergency Contact Number",
      name: "basicField.emengencyNumber",
      type: "phoneNumber",
      placeholder: "Emergency Contact Number",
      required: true,
    },
    {
      label: "D.O.B.",
      name: "basicField.dob",
      type: "date",
      placeholder: "D.O.B",
      required: true,
    },
    {
      label: "Designation",
      name: "basicField.jobRole",
      type: "text",
      placeholder: "Designation",
      required: true,
    },
    {
      label: "Department",
      name: "basicField.department",
      type: "text",
      placeholder: "Department",
      required: true,
    },
    {
      label: "Job Location",
      name: "basicField.jobLocation",
      type: "select",
      placeholder: "Job Location",
      options: [
        { value: "BIHAR", label: "BIHAR" },
        { value: "DEHRADUN", label: "DEHRADUN" },
      ],
      required: true,
    },
    {
      label: "Personal Email id",
      name: "basicField.personalEmail",
      type: "text",
      placeholder: "Email",
      required: true,
    },
    {
      label: "CTC",
      name: "basicField.ctc",
      type: "text",
      placeholder: "CTC",
      required: true,
    },
    {
      label: "PAN Card Number",
      name: "basicField.pan",
      type: "text",
      placeholder: "PAN Card Number",
      required: true,
    },
    {
      label: "Aadhar Card Number",
      name: "basicField.aadhar",
      type: "number",
      placeholder: "Aadhar Card Number",
      required: true,
    },
    {
      label: "Address",
      name: "basicField.address",
      type: "textarea",
      placeholder: "Address",
      required: true,
    },
    {
      label: "Gender",
      name: "basicField.gender",
      type: "select",
      options: [
        { value: "Male", label: "Male" },
        { value: "Female", label: "Female" },
        { value: "Other", label: "Other" },
      ],
      required: true,
    },
    {
      label: "Status",
      name: "basicField.status",
      type: "select",
      options: [
        { value: "ACTIVE", label: "Active" },
        { value: "INACTIVE", label: "Inactive" },
      ],
      required: true,
    },
    {
      label: "Joining Date",
      name: "basicField.doj",
      type: "date",
      placeholder: "Joining Date",
      required: true,
    },
    {
      label: "Last Working Date (if applicable)",
      name: "basicField.lwd",
      type: "date",
      placeholder: "Last Working Date",
      required: false,
    },
    {
      label: "Role",
      name: "basicField.role",
      type: "select",
      options: [
        // { value: "ADMIN", label: "admin" },
        { value: "EMPLOYEE", label: "EMPLOYEE" },
      ],
      required: true,
    },
    {
      label: "Give all permissions",
      name: "permissions",
      type: "checkbox",
      trueValue: "all",
      falseValue: "choose",
    },
    {
      label: "Students",
      name: "permissions.student",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Faculty",
      name: "permissions.faculty",
      type: "multiselect",
      display: "horizontal",
      options: [
        { value: "view", label: "view" },
        { value: "add", label: "add" },
        { value: "edit", label: "edit" },
        { value: "delete", label: "delete" },
      ],
      dependsOn: { field: "permissions", valueIsNot: "all" },
    },
    {
      label: "Profile picture",
      name: "basicField.profilePic",
      type: "file",
      required: true,
    },
  ],
  bankFields: [
    {
      label: "Bank Account name",
      name: "bankField.bankName",
      type: "text",
      required: true,
    },
    {
      label: "Bank Account number",
      name: "bankField.bankAccountNumber",
      type: "text",
      required: true,
    },
    {
      label: "IFSC code",
      name: "bankField.ifscCode",
      type: "text",
      required: true,
    },
    {
      label: "Bank Passbook",
      name: "bankField.passbook",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
  ],
  docFields: [
    {
      label: "Aadhar Document ",
      name: "docField.adharDocument",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "PAN Document ",
      name: "docField.panDocument",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "10th Marksheet ",
      name: "docField.tenthMarksheet",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "12th Marksheet ",
      name: "docField.twelvethMarksheet",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "UG Marksheet ",
      name: "docField.ugMarksheet",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "PG Marksheet ",
      name: "docField.pgMarksheet",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Resume ",
      name: "docField.resume",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Last Company salary slip ",
      name: "docField.salarySlip",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Last Company Experience letter ",
      name: "docField.expLetter",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Last Company Internship Certificate (if applicable) ",
      name: "docField.intershipcert",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Last Company Offer letter",
      name: "docField.offerLetter",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Other Documents ",
      name: "docField.otherdoc",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
  ],
  companyFields: [
    {
      label: "Company Contract",
      name: "companyField.contract",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Internship Certificate ",
      name: "docField.intershipcert",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Company Offer letter",
      name: "companyField.offerLetter",
      type: "file",
      required: true,
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Company ID",
      name: "companyField.idCard",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Relieving letter",
      name: "companyField.relievingLetter",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Experience letter",
      name: "companyField.expLetter",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },

    {
      label: "Salary slip",
      name: "companyField.salarySlip",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
    {
      label: "Other Documents ",
      name: "docField.otherdoc",
      type: "file",
      folder: "CoachingManagementSystem/FacultyDetails",
    },
  ],
  salaryFields: [
    {
      label: "Basic Salary",
      name: "earning.basicSalary",
      type: "number",
      required: true,
    },
    {
      label: "HRA (House Rent Allowance)",
      name: "earning.hra",
      type: "number",
    },
    {
      label: "Telephone Reimbursement",
      name: "earning.telephoneReimbursement",
      type: "number",
    },
    {
      label: "Bonus",
      name: "earning.bonus",
      type: "number",
    },
    {
      label: "LTA (Leave Travel Allowance)",
      name: "earning.lta",
      type: "number",
    },
    {
      label: "Special Allowance / Petrol Allowance",
      name: "earning.specialAllowancePetrolAllowance",
      type: "number",
    },
    {
      label: "Incentive",
      name: "earning.incentive",
      type: "number",
    },
  ],
  taxFields: [
    {
      label: "Income Tax",
      name: "tax.incomeTax",
      type: "number",
      required: true,
    },
    {
      label: "Provident Fund",
      name: "tax.providentFund",
      type: "number",
    },
    {
      label: "Professional Tax",
      name: "tax.professionalTax",
      type: "number",
    },
  ],
};
//b2bFields
export const b2bFields = [
  {
    label: "Business Type",
    name: "basic.businessType",
    type: "select",
    options: [
      { value: "College", label: "College" },
      { value: "School", label: "School" },
      { value: "Agent", label: "Agent" },
      { value: "Consultancy", label: "Consultancy" },
      { value: "Others", label: "Others" },
    ],
    required: true,
  },
  {
    label: "Name of Institution / Agency",
    name: "basic.institutionName",
    type: "text",
    required: true,
  },
  {
    label: "Contact Person Name",
    name: "basic.contactPersonName",
    type: "text",
    required: true,
  },
  {
    label: "Designation",
    name: "basic.designation",
    type: "text",
  },
  {
    label: "Email Address",
    name: "basic.emailAddress",
    type: "email",
    required: false,
  },
  {
    label: "Phone Number",
    name: "basic.phoneNumber",
    type: "mobile",
    required: true,
    isMobileField: true,
  },
  {
    label: "Alternate Phone Number",
    name: "basic.alternatePhoneNumber",
    type: "tel",
  },
  {
    label: "Website (if any)",
    name: "basic.website",
    type: "url",
  },
  {
    label: "Country",
    name: "address.country",
    type: "select",
    options: [
      { value: "USA", label: "USA" },
      { value: "CANADA", label: "CANADA" },
      { value: "UK", label: "UK" },
      { value: "FINLAND", label: "FINLAND" },
      { value: "MALTA", label: "MALTA" },
      { value: "LUXEMBOURG", label: "LUXEMBOURG" },
      { value: "CHINA", label: "CHINA" },
      { value: "NEPAL", label: "NEPAL" },
      { value: "BANGLADESH", label: "BANGLADESH" },
      { value: "BHUTAN", label: "BHUTAN" },
      { value: "NEW ZEALAND", label: "NEW ZEALAND" },
      { value: "SINGAPORE", label: "SINGAPORE" },
      { value: "SWITZERLAND", label: "SWITZERLAND" },
      { value: "SWEDEN", label: "SWEDEN" },
      { value: "GERMANY", label: "GERMANY" },
      { value: "GEORGIA", label: "GEORGIA" },
      { value: "AUSTRIA", label: "AUSTRIA" },
      { value: "AUSTRALIA", label: "AUSTRALIA" },
      { value: "RUSSIA", label: "RUSSIA" },
      { value: "ITALY", label: "ITALY" },
      { value: "INDIA", label: "INDIA" },
    ],
    allowTextEntry: true,
    required: true,
  },
  {
    label: "State",
    name: "address.state",
    type: "select",
    options: [],
    // required: true,
  },
  {
    label: "City",
    name: "address.city",
    type: "select",
    options: [],
    // required: true,
  },
  {
    label: "Pincode",
    name: "address.pincode",
    type: "number",
    required: true,
  },
  {
    label: "Full Address",
    name: "address.fullAddress",
    type: "textarea",
    required: true,
  },
  {
    label: "Google Map Link",
    name: "address.googleMapLink",
    type: "url",
    required: false,
  },
  {
    label: "Nature of Partnership",
    name: "details.natureOfPartnership",
    type: "select",
    options: [
      { value: "Lead Sharing", label: "Lead Sharing" },
      { value: "Event Collaboration", label: "Event Collaboration" },
      { value: "Commission-based", label: "Commission-based" },
      { value: "Others", label: "Others" },
    ],
    required: false,
  },
  {
    label: "Services Agreed Upon",
    name: "details.servicesAgreedUpon",
    type: "multi-select",
    options: [
      { value: "Counseling", label: "Counseling" },
      { value: "Admissions", label: "Admissions" },
      { value: "Visa", label: "Visa" },
      { value: "Marketing", label: "Marketing" },
      { value: "Others", label: "Others" },
    ],
    required: false,
  },
  {
    label: "Agreement Start Date",
    name: "details.agreementStartDate",
    type: "date",
    required: false,
  },
  {
    label: "Agreement End Date",
    name: "details.agreementEndDate",
    type: "date",
    required: false,
  },
  {
    label: "Partnership Status",
    name: "details.partnershipStatus",
    type: "select",
    options: [
      { value: "Active", label: "Active" },
      { value: "Inactive", label: "Inactive" },
      { value: "Under Discussion", label: "Under Discussion" },
      { value: "Terminated", label: "Terminated" },
    ],
    required: false,
  },
  {
    label: "Commission Type",
    name: "paymentInfo.commissionType",
    type: "select",
    options: [
      { value: "Fixed", label: "Fixed" },
      { value: "Percentage", label: "Percentage" },
      { value: "No Commission", label: "No Commission" },
    ],
    required: false,
  },
  {
    label: "Commission Rate or Amount",
    name: "paymentInfo.commissionRateOrAmount",
    type: "text",
    required: false,
  },
  {
    label: "Payment Terms",
    name: "paymentInfo.paymentTerms",
    type: "text",
    required: false,
  },
  {
    label: "Bank Name",
    name: "paymentInfo.bankName",
    type: "text",
    required: false,
  },
  {
    label: "Account Holder Name",
    name: "paymentInfo.accountHolderName",
    type: "text",
    required: false,
  },
  {
    label: "Account Number",
    name: "paymentInfo.accountNumber",
    type: "number",
    required: false,
  },
  {
    label: "IFSC Code",
    name: "paymentInfo.ifscCode",
    type: "text",
    required: false,
  },
  {
    label: "UPI ID",
    name: "paymentInfo.upiId",
    type: "text",
    required: false,
  },
  {
    label: "Upload MOU / Agreement",
    name: "documentation.mouAgreement",
    type: "file",
    accept: ".pdf,.doc,.docx",
    required: false,
    folder: "b2b/mouAgreement",
  },
  {
    label: "Upload ID Proof (for Agent)",
    name: "documentation.idProof",
    type: "file",
    accept: "image/*,.pdf",
    required: false,
    folder: "b2b/IdProff",
  },
  {
    label: "Upload Partner Logo",
    name: "documentation.partnerLogo",
    type: "file",
    accept: "image/jpeg,image/png",
    required: false,
    folder: "b2b/partnerLogo",
  },
  {
    label: "Date of Last Interaction",
    name: "remarks.dateOfLastInteraction",
    type: "date",
    required: true,
  },
  {
    label: "Remark (if any)",
    name: "remarks.reminremarkders",
    type: "textarea",
    required: false,
  },
];
